#!/usr/bin/bash
ID=2931
IMG_PATH=$HOME/newDisk/img/screenshot;

case $1 in
    full)
       cd  $IMG_PATH;
       scrot
       cd -
       dunstify -t 4000 -r $ID "Full screenshot in $IMG_PATH"
       ;;
    win)
       cd  $IMG_PATH
       scrot -u
       cd -
       dunstify -t 4000 -r $ID "Current window screenshot in $IMG_PATH"
       ;;
   *)
       dunstify -t 4000 -r $ID "Unknown usage for scrot, screenshot aborted"
esac
