#!/usr/bin/python
"""
A script to recover my directory structure.
"""

from pathlib import Path
import os
import sys
from typing import List, Optional, Callable


class DirNode:
    node_type = ["folder", "file"]
    indent = 0

    def __init__(self, type: str, name: str,
                 children: Optional[List['DirNode']] = None):
        self.visited = False
        self.name = name
        self.parent: Optional['DirNode'] = None

        if type in DirNode.node_type:
            self.type = type
        else:
            raise AttributeError("Wrong key for node")

        self.children: List[DirNode]
        if children is not None:
            self.children = children
            for n in children:
                n.parent = self
        else:
            self.children = []

    def traverse(self, cb: Callable):
        if self.visited:
            return
        cb(self)
        DirNode.indent += 4
        if self.type == "file" or len(self.children) == 0:
            DirNode.indent -= 4
            return
        for n in self.children:
            n.traverse(cb)
        DirNode.indent -= 4

    def __str__(self) -> str:
        res = DirNode.indent * " "
        res += f"<DirNode name={self.name}, type={self.type}>"
        return res

    __repr__ = __str__


paths: List[Path] = []


def callback(self: DirNode):
    paths = [self.name]
    currnet = self
    parent = currnet.parent
    while parent is not None:
        paths.append(parent.name)
        currnet = parent
        parent = parent.parent

    top = paths.pop()
    path: Path = Path(top)
    for p in reversed(paths):
        path = path / Path(p)

    global paths
    paths.append(path)


math = DirNode(type="folder", name="math")
book = DirNode(type="folder", name="book", children=[math])

docs = DirNode(type="folder", name="docs")
Repo = DirNode(type="folder", name="Repo")

screenshot = DirNode(type="folder", name="screenshot")
img = DirNode(type="folder", name="img", children=[screenshot])


pj = DirNode(type="folder", name="apj")
newDisk = DirNode(type="folder", name="newDisk", children=[
    book, img, Repo
])
yeetDisk = DirNode(type="folder", name="yeetDisk", children=[docs])


if __name__ == "__main__":
    assert len(sys.argv) == 0

    h: str = sys.argv[1]
    home_path = Path(h).resolve()
    os.chdir(home_path)
